### ISSUE TITLE
too many training process start

### ISSUE THREAD

**Issue by zhuzhikui** [fastnlp/JointCwsParser#2]
![QQ截图20200102111953](https://user-images.githubusercontent.com/38184263/71650593-e83af400-2d51-11ea-99c9-facdd20b7653.png)
![QQ截图20200102111953](https://user-images.githubusercontent.com/38184263/71650636-38b25180-2d52-11ea-90af-5844b8658e82.png)

It seems the program  initializes many training process

**Comment by zhuzhikui** [comment]
After training process beginning, it seems that the program turn to data preparing again and run another training process.

"""
Epoch 1/3:   0%|          | 0/936 [00:00<?, ?it/s, loss:{0:<6.5f}]training epochs started 2020-01-02-11-16-14
Read cache from caches/HIT.pkl.
In total 3 datasets:
	dev has 1700 instances.
	test has 2416 instances.
	train has 39832 instances.
"""

"""
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
"""

**Comment by zhuzhikui** [comment]
I change the "num_workers" from 2 to 0 so that I solve the problem

**Comment by yhcc** [comment]
This has something to do with the system. We encountered this problem previously, however, we haven't found a solution other than setting num_workers to 0.
